export const brandDatas = [
    {
      id: 1,
      name: "Brand 1",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand1-thumbnail.png",
      banner: "/images/brand1-banner.png",
      description: "Brand 1 is known for its excellence in Category A.",
      status: "active",
    },
    {
      id: 2,
      name: "Brand 2",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand2-thumbnail.png",
      banner: "/images/brand2-banner.png",
      description: "Brand 2 offers a wide range of products in Category B.",
      status: "inactive",
    },
    {
      id: 3,
      name: "Brand 3",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand3-thumbnail.png",
      banner: "/images/brand3-banner.png",
      description: "Brand 3 specializes in Category C with premium offerings.",
      status: "active",
    },
    {
      id: 4,
      name: "Brand 4",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand4-thumbnail.png",
      banner: "/images/brand4-banner.png",
      description: "Brand 4 offers innovative solutions in Category D.",
      status: "active",
    },
    {
      id: 5,
      name: "Brand 5",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand5-thumbnail.png",
      banner: "/images/brand5-banner.png",
      description: "Brand 5 focuses on sustainability in Category E.",
      status: "inactive",
    },
    {
      id: 6,
      name: "Brand 6",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand6-thumbnail.png",
      banner: "/images/brand6-banner.png",
      description: "Brand 6 is a leader in the tech space of Category F.",
      status: "active",
    },
    {
      id: 7,
      name: "Brand 7",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand7-thumbnail.png",
      banner: "/images/brand7-banner.png",
      description: "Brand 7 is a premium brand in Category G.",
      status: "inactive",
    },
    {
      id: 8,
      name: "Brand 8",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand8-thumbnail.png",
      banner: "/images/brand8-banner.png",
      description: "Brand 8 is revolutionizing Category H with cutting-edge products.",
      status: "active",
    },
    {
      id: 9,
      name: "Brand 9",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand9-thumbnail.png",
      banner: "/images/brand9-banner.png",
      description: "Brand 9 is redefining luxury in Category I.",
      status: "active",
    },
    {
      id: 10,
      name: "Brand 10",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand10-thumbnail.png",
      banner: "/images/brand10-banner.png",
      description: "Brand 10 is famous for its innovative designs in Category J.",
      status: "inactive",
    },
    {
      id: 11,
      name: "Brand 11",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand11-thumbnail.png",
      banner: "/images/brand11-banner.png",
      description: "Brand 11 is a strong player in Category K.",
      status: "active",
    },
    {
      id: 12,
      name: "Brand 12",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand12-thumbnail.png",
      banner: "/images/brand12-banner.png",
      description: "Brand 12 is pushing the boundaries in Category L.",
      status: "inactive",
    },
    {
      id: 13,
      name: "Brand 13",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand13-thumbnail.png",
      banner: "/images/brand13-banner.png",
      description: "Brand 13 excels in providing innovative solutions in Category M.",
      status: "active",
    },
    {
      id: 14,
      name: "Brand 14",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand14-thumbnail.png",
      banner: "/images/brand14-banner.png",
      description: "Brand 14 is the leader in Category N.",
      status: "inactive",
    },
    {
      id: 15,
      name: "Brand 15",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand15-thumbnail.png",
      banner: "/images/brand15-banner.png",
      description: "Brand 15 offers premium products in Category O.",
      status: "active",
    },
    {
      id: 16,
      name: "Brand 16",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand16-thumbnail.png",
      banner: "/images/brand16-banner.png",
      description: "Brand 16 is an innovator in Category P.",
      status: "inactive",
    },
    {
      id: 17,
      name: "Brand 17",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand17-thumbnail.png",
      banner: "/images/brand17-banner.png",
      description: "Brand 17 is expanding in Category Q.",
      status: "active",
    },
    {
      id: 18,
      name: "Brand 18",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand18-thumbnail.png",
      banner: "/images/brand18-banner.png",
      description: "Brand 18 is a household name in Category R.",
      status: "active",
    },
    {
      id: 19,
      name: "Brand 19",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand19-thumbnail.png",
      banner: "/images/brand19-banner.png",
      description: "Brand 19 leads the market in Category S.",
      status: "inactive",
    },
    {
      id: 20,
      name: "Brand 20",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand20-thumbnail.png",
      banner: "/images/brand20-banner.png",
      description: "Brand 20 is an industry leader in Category T.",
      status: "active",
    },
    {
      id: 21,
      name: "Brand 21",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand21-thumbnail.png",
      banner: "/images/brand21-banner.png",
      description: "Brand 21 excels in the lifestyle market of Category U.",
      status: "active",
    },
    {
      id: 22,
      name: "Brand 22",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand22-thumbnail.png",
      banner: "/images/brand22-banner.png",
      description: "Brand 22 focuses on high-end products in Category V.",
      status: "inactive",
    },
    {
      id: 23,
      name: "Brand 23",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand23-thumbnail.png",
      banner: "/images/brand23-banner.png",
      description: "Brand 23 specializes in technology in Category W.",
      status: "active",
    },
    {
      id: 24,
      name: "Brand 24",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand24-thumbnail.png",
      banner: "/images/brand24-banner.png",
      description: "Brand 24 offers sustainable products in Category X.",
      status: "inactive",
    },
    {
      id: 25,
      name: "Brand 25",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand25-thumbnail.png",
      banner: "/images/brand25-banner.png",
      description: "Brand 25 is a pioneer in the health industry, Category Y.",
      status: "active",
    },
    {
      id: 26,
      name: "Brand 26",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand26-thumbnail.png",
      banner: "/images/brand26-banner.png",
      description: "Brand 26 focuses on sports in Category Z.",
      status: "inactive",
    },
    {
      id: 27,
      name: "Brand 27",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand27-thumbnail.png",
      banner: "/images/brand27-banner.png",
      description: "Brand 27 is revolutionizing home products in Category A.",
      status: "active",
    },
    {
      id: 28,
      name: "Brand 28",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand28-thumbnail.png",
      banner: "/images/brand28-banner.png",
      description: "Brand 28 offers premium beauty products in Category B.",
      status: "inactive",
    },
    {
      id: 29,
      name: "Brand 29",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand29-thumbnail.png",
      banner: "/images/brand29-banner.png",
      description: "Brand 29 is a global leader in Category C.",
      status: "active",
    },
    {
      id: 30,
      name: "Brand 30",
      url: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      logo: "https://img.daisyui.com/images/profile/demo/2@94.webp",
      thumbnail: "/images/brand30-thumbnail.png",
      banner: "/images/brand30-banner.png",
      description: "Brand 30 has become an icon in Category D.",
      status: "inactive",
    },
  ];
  